export enum Branches {
  All = 'All',
  Automotive_Industry = 'Automotive_Industry',
  Construction_RealEstate = 'Construction_RealEstate',
  Education = 'Education',
  Service = 'Service',
  Energy_Industry = 'Energy_Industry',
  Finance_Marketing_Insurance = 'Finance_Marketing_Insurance',
  Trade = 'Trade',
  Hotels_Restaurants = 'Hotels_Restaurants',
  Industry = 'Industry',
  IT_Telecommunications = 'IT_Telecommunications',
  Agriculture = 'Agriculture',
  Media_Internet = 'Media_Internet',
  Medicine_Health = 'Medicine_Health',
  Fashion_Beauty = 'Fashion_Beauty',
  Food_Beverage = 'Food_Beverage',
  Public_Service = 'Public_Service',
  Organisation = 'Organisation',
  Legal = 'Legal',
  Other = 'Other',
  Sports_Rekreation = 'Sports_Rekreation',
  Transport_Traffic_Logistik = 'Transport_Traffic_Logistik',
  Science_Research = 'Science_Research',
}
