import { Component } from '@angular/core';
@Component({ selector: 'app-projects-page', standalone: false, template: `<section><div class="flex flex-wrap items-end justify-between gap-4"><div><div class="text-[10px] font-semibold tracking-[.16em] text-[#7e8d72]">MAKE IT REAL ✦</div><h1 class="mt-2 text-3xl font-semibold tracking-tight">Your projects</h1><p class="mt-2 text-sm text-stone-500">A home for the work you’re proud to put your name on.</p></div><button class="rounded-xl bg-[#43563c] px-4 py-2.5 text-sm font-medium text-white hover:bg-[#35472f]" (click)="notice = 'Your next project starts with one small step.'">＋ &nbsp; New project</button></div><div class="mt-7 flex gap-2 text-xs"><button class="rounded-full bg-[#e9ede4] px-3 py-2 font-medium text-[#536649]">All projects&nbsp; 3</button><button class="rounded-full border border-stone-200 bg-white px-3 py-2 text-stone-500">In progress&nbsp; 2</button><button class="rounded-full border border-stone-200 bg-white px-3 py-2 text-stone-500">Planning&nbsp; 1</button></div>@if(notice){<p class="mt-4 text-sm text-[#536649]">{{notice}}</p>}<div class="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3">@for (project of projects; track project.name) {<article class="rounded-2xl border border-stone-200/80 bg-white p-5 transition hover:-translate-y-0.5 hover:shadow-md"><div class="flex items-center justify-between"><span class="grid size-11 place-items-center rounded-2xl text-lg" [class]="project.color">{{project.icon}}</span><span class="rounded-full bg-[#e9f0e9] px-2.5 py-1 text-[10px] font-medium text-[#617c68]">{{project.status}}</span></div><h2 class="mt-5 text-lg font-semibold">{{project.name}}</h2><p class="mt-1 min-h-10 text-sm leading-5 text-stone-500">{{project.description}}</p><div class="mt-5 flex justify-between text-[11px] text-stone-400"><span>{{project.category}}</span><span>{{project.due}}</span></div><div class="mt-4 flex justify-between text-xs"><span class="text-stone-500">Progress</span><b>{{project.progress}}%</b></div><div class="mt-2 h-1.5 rounded-full bg-stone-100"><div class="h-full rounded-full bg-[#879778]" [style.width.%]="project.progress"></div></div></article>}</div></section>` })
export class ProjectsPage {
  notice=''; projects = [
    { icon:'✳',color:'bg-[#eeebf7] text-[#766b9d]',name:'Portfolio refresh',description:'A thoughtful home for the work I want to do more of.',category:'Design & personal brand',due:'Due Oct 04',status:'In progress',progress:72 },
    { icon:'◉',color:'bg-[#f6ece5] text-[#aa7955]',name:'UX case study',description:'Making everyday banking feel a little more human.',category:'Product thinking',due:'Due Oct 12',status:'In progress',progress:46 },
    { icon:'✦',color:'bg-[#e8f1ed] text-[#688578]',name:'Learn Figma variables',description:'A small skill investment with a big creative payoff.',category:'Skill building',due:'No due date',status:'Planning',progress:28 }
  ];
}
